// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQz4yBK8k87Fm3tn_0h7Y5n-cnPUYAlY',
    appId: '1:708688301387:web:03c571efd72eb70c1a6cce',
    messagingSenderId: '708688301387',
    projectId: 'smart-attendance-applica-6d440',
    authDomain: 'smart-attendance-applica-6d440.firebaseapp.com',
    storageBucket: 'smart-attendance-applica-6d440.appspot.com',
    measurementId: 'G-J6LB5M9TSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCewwVPsclu-z-zCgkW3Rzf0Nv8hgHrdaI',
    appId: '1:708688301387:android:5ec33ca784d4d5711a6cce',
    messagingSenderId: '708688301387',
    projectId: 'smart-attendance-applica-6d440',
    storageBucket: 'smart-attendance-applica-6d440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9_hYS4uQtzzlJGJfTkQeKb5i7cKjMV_4',
    appId: '1:708688301387:ios:a8438dcbae1160081a6cce',
    messagingSenderId: '708688301387',
    projectId: 'smart-attendance-applica-6d440',
    storageBucket: 'smart-attendance-applica-6d440.appspot.com',
    iosBundleId: 'com.example.smartAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9_hYS4uQtzzlJGJfTkQeKb5i7cKjMV_4',
    appId: '1:708688301387:ios:c2412a01e70135f81a6cce',
    messagingSenderId: '708688301387',
    projectId: 'smart-attendance-applica-6d440',
    storageBucket: 'smart-attendance-applica-6d440.appspot.com',
    iosBundleId: 'com.example.smartAttendanceApp.RunnerTests',
  );
}
